### ISSUE TITLE
Icon name consistency 

### ISSUE THREAD

**Issue by antonreshetov** [Iconscout/unicons#3]
There are two icons with the same name but with different spelling `snow-flake` and `snowflake`

**Comment by OwenMelbz** [comment]
Is that not the same as how don’t awesome has aliases for the icons to make them more semantic?

**Comment by tarunmangukiya** [comment]
@antonreshetov True there are 2 icons with the same name. But they both have different designs. And as @OwenMelbz said, we're following standard names so that it becomes easy for everyone to use the icons.

**Comment by antonreshetov** [comment]
@tarunmangukiya ok then i don't understand it `snowflake`, `snowflake-alt` and `snow-flake`. Why there are two icons that have the same spelling but different design + suffix and an icon with a different spelling

**Comment by tarunmangukiya** [comment]
We've seen users using different type of snowflakes and even purchasing full pack of snowflake icons. Thus we thought to giving basic designs in the icons itself, so that users can use as per their convenience.

About name, I am not sure whether we should change it. Do suggest the names which you think it's appropriate. :D

**Comment by antonreshetov** [comment]
Now I have solved the problem. I had the task of separating the icons into separate components. Component names by convention in Vue should be in camelcase. As a result, there were problems when importing UniSnowFlake and UniSnowflake. Now I decided to connect only the necessary icons in a different way. Therefore, there is no problem.

Let it be as it is with the names)
